# Default configuration (Common for all profiles)
spring.application.name=modulith-service
spring.threads.virtual.enabled=true

# Database Configuration (Common)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${JAVA_DB_USERNAME}
spring.datasource.password=${JAVA_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis Configuration (Common)
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# Security
jwt.secret=${JWT_SECRET}

# Common Integrations
mail.host=${MAIL_HOST}
mail.port=${MAIL_PORT}
mail.username=${MAIL_USERNAME}
mail.password=${MAIL_PASSWORD}

# Default Active Profile
spring.profiles.active=dev
