# DEV Profile Configuration (application-dev.properties)
# Default profile

# Database - Dev specific
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dev}
spring.datasource.username=${JAVA_DB_USERNAME:postgres}
spring.datasource.password=${JAVA_DB_PASSWORD:123Vasu456}
spring.datasource.hikari.maximum-pool-size=50
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Payment - Razorpay (TEST)
razorpay.key.id=${RAZORPAY_TEST_KEY_ID:rzp_test_S5MEGtoqd7w5Pb}
razorpay.key.secret=${RAZORPAY_TEST_KEY_SECRET:xFvJG9JDtC13t3ARmvMBbAWs}
razorpay.webhook.secret=${RAZORPAY_TEST_WEBHOOK_SECRET:webhook_secret_keyha@123}

# Shipping - Shiprocket (TEST/DEV)
shiprocket.email=${SHIPROCKET_TEST_EMAIL:your_shiprocket_email@example.com}
shiprocket.password=${SHIPROCKET_TEST_PASSWORD:your_shiprocket_password}
shiprocket.channel.id=${SHIPROCKET_TEST_CHANNEL_ID:}

shiprocket.test.email=${SHIPROCKET_TEST_EMAIL:your_shiprocket_email@example.com}
shiprocket.test.password=${SHIPROCKET_TEST_PASSWORD:your_shiprocket_password}
shiprocket.test.channel.id=${SHIPROCKET_TEST_CHANNEL_ID:}

shiprocket.prod.email=${SHIPROCKET_PROD_EMAIL:vaabhiofficial@gmail.com}
shiprocket.prod.password=${SHIPROCKET_PROD_PASSWORD:Charitha@23.}
shiprocket.prod.channel.id=${SHIPROCKET_PROD_CHANNEL_ID:9308067}



# Logging
logging.level.root=INFO
logging.level.com.app=INFO
management.endpoints.web.exposure.include=*
