server:
  port: 8083
  http2:
    enabled: true
  http3:
    enabled: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true

spring:
  application:
    name: marketplace-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dev}
    username: ${JAVA_DB_USERNAME:postgres}
    password: ${JAVA_DB_PASSWORD:123Vasu456}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Kolkata
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

marketplace:
  amazon:
    secret: ${AMAZON_WEBHOOK_SECRET:mock-amazon-secret}
  flipkart:
    secret: ${FLIPKART_WEBHOOK_SECRET:mock-flipkart-secret}
  ondc:
    secret: ${ONDC_WEBHOOK_SECRET:mock-ondc-secret}


logging:
  level:
    com.app.marketplace: DEBUG
