#db config
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dev}
spring.datasource.username=${JAVA_DB_USERNAME:postgres}
spring.datasource.password=${JAVA_DB_PASSWORD:123Vasu456}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

# Redis Caching
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6380}
cache.type=redis

#image
project.image=images/
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#JWT Security Key
jwt_secret=${JAVA_JWT_SECRET:cl$ksc^nas%lkdm!cz@xclk#as&dmka;s28*392da%jskd#n9827@3498%}

# ERPNext Integration
erpnext.api.url=${ERPNEXT_API_URL:http://localhost:8000/api/resource/Item}
erpnext.api.key=${ERPNEXT_API_KEY}
erpnext.api.secret=${ERPNEXT_API_SECRET}

#Swagger OpenAPI
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.doc-expansion=false

# Logging
logging.level.org.springframework.security=debug