spring.application.name=product-service
server.port=8082
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
server.compression.min-response-size=1024
server.http2.enabled=true
server.http3.enabled=true

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dev}
spring.datasource.username=${JAVA_DB_USERNAME:postgres}
spring.datasource.password=${JAVA_DB_PASSWORD:123Vasu456}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}

# Actuator Config
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.health.redis.enabled=true

# Infrastructure
spring.data.redis.host=${REDIS_HOST:localhost}
