spring.application.name=product-service
server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dev}
spring.datasource.username=${JAVA_DB_USERNAME:postgres}
spring.datasource.password=${JAVA_DB_PASSWORD:123Vasu456}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
